### ISSUE TITLE
Juli

### ISSUE THREAD

**Issue by Fabian-Martinez-Rincon** [OmgCopito95/CADP#1]
Hola Juli, creo que faltaría un ejercicio completo en el que se calculan las memorias y el tiempo. Yo hice uno por si lo queres mirar
https://github.com/Fabian-Martinez1/CADP espero te sirva :D

**Comment by OmgCopito95** [comment]
Buenisimo!! Habría que hacer un programita que lo haga automático así pueden comparar resultados ☺️

**Comment by Fabian-Martinez-Rincon** [comment]
Sisi, tengo un repositorio para hacerlo pero siempre me cuelgo jaja, yo quería leer cualquier programa con expresiones regulares, pero solo me contaría ciertas estructuras y siempre valdrían uno. Tipo, lo que tendría que hacer es con la tabla que ya tengo armada, en cuanto el programa lea, ir sumando dependiendo las cosas que me encuentre, en relacion a la tabla. Si encontras info avísame porfa jaja
